### ISSUE TITLE
Use local IPFS node for larger file (volume/code) uploads

### ISSUE THREAD

**Issue by BjrInt** [aleph-im/front-aleph-cloud-page#58]
# Problem

Uploading large files through the console is not working.

# Solution

Use a local IPFS ([helia](https://github.com/ipfs/helia)) and pin the file using a STORE message instead. 

# Pitfalls

- Make sure the file is properly downloaded on the Aleph IPFS node before it is gc'ed

**Comment by philogicae** [comment]
We had many issues with Helia, so we dropped it in favor of a dedicated endpoint (implemented when we added the web3 hosting feature). I close this issue for now, we can open a new one if the idea of implementing Helia comes back on the table.
